Initial Python - MongoDB commit
rlennon/Doodle pull request #14
Opened 2019-03-08 01:35 UTC by L00144438

Very basic code to test mongoDB using pymongo
TODO:
Add requisites 
Tidy Code
Add usage

2019-03-08 08:00 UTC, ghost requested changes
all these .idea metafiles are not relevent? if not, they will just clutter up the repo. perhaps watch when you "git add *" or create .gitignore file

2019-03-08 08:02 UTC, peterti commented
good job! our first actual code!

2019-03-08 10:02 UTC, ghost approved these changes

2019-03-11 22:47 UTC, cjfarrelly approved these changes
👍

2019-03-14 11:01 UTC, merged