Adding the requirements document & putting a link to it in the README
rlennon/Doodle pull request #17
Opened 2019-03-12 19:16 UTC by l00144427

Renamed the document to requirements.md & put a link to it in the README.md file

2019-03-12 20:45 UTC, rlennon requested changes

2019-03-12 20:45 UTC, rlennon commented on content/requirements.md
> +* Dimensions can be entered.
Additional information would be useful such as the number of rooms, special room requirements and so on

2019-03-12 20:45 UTC, rlennon commented on content/requirements.md
> +Do we need to worry about adding & deleting branches?
Yes

2019-03-12 20:45 UTC, rlennon commented on content/requirements.md
> +Do we need to worry about adding & deleting users?
yes

2019-03-13 18:00 UTC, l00144427 commented
I added additional information to the Users, Data Entry Requirements Details & Other Details sections and also removed the Outstanding Questions section based on the feedback.
Please review and approve if acceptable.

2019-03-13 19:55 UTC, cjfarrelly approved these changes
lgtm!

2019-03-15 11:32 UTC, L00144438 approved these changes
Need to discuss the requirements!

2019-03-17 14:13 UTC, l00144427 commented on content/requirements.md
> +* Dimensions can be entered.
I have added some changes based on your comments, please review & approve if you think it's ok.

2019-03-19 16:29 UTC, l00119705 approved these changes

2019-03-19 20:54 UTC, l00073976 approved these changes
lgtm

2019-03-19 22:58 UTC, rlennon approved these changes
LGTM

2019-03-21 20:08 UTC, merged