Doodle Python UI POC
rlennon/Doodle pull request #19
Opened 2019-03-13 03:58 UTC by l00119705

I've created a simple enough UI POC just to test what was needed to write a Web UI in Python. 

Not quite sure how easy this will be to pull down and run due to my Python virtual environment being specific to my directories. 

![image](https://user-images.githubusercontent.com/39068555/54252569-4a1c3a00-4543-11e9-9ce0-ba6b02157232.png)

Additional Packages imported for this POC:
Flask (for web development)
Flask-WTF (Forms)

& bootstrap was also used for ease of styling

2019-03-13 04:11 UTC, l00119705 commented
had to delete my venv from the commit because there was 165k changes. definitely a lot of unnecessary files in the commit

2019-03-13 08:56 UTC, cjfarrelly approved these changes
Great stuff! I'll pull it down later and take a look

2019-03-13 17:00 UTC, ghost requested changes
are all these .idea metafiles relevant?

2019-03-13 17:02 UTC, l00119705 commented
@peterti they were auto generated when I had the venv there, I will delete everything bar they python/css/html files

2019-03-13 17:22 UTC, peterti commented
> @peterti they were auto generated when I had the venv there, I will delete everything bar they python/css/html files

great. thank you

otherwise, good work!

2019-03-19 14:51 UTC, peterti commented
@l00119705 can you have a look again at this PR? perhaps it is time to close it

2019-03-19 15:30 UTC, ghost reviewed
ive noticed the folder structure is messed up here also. you have added it under content/
it should be at the top level (src/POC)

2019-03-19 15:31 UTC, ghost approved these changes
perhaps cleanup .idea files

2019-03-19 16:30 UTC, l00119705 commented
I will clean up tonight, thanks @peterti

2019-03-19 22:18 UTC, merged